services:
  bg-removal:
      image: danielgatis/rembg
      command: s
      ports:
        - 8090:5000
  sticker-generator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BG_REMOVAL_BASE_URL=http://bg-removal:5000
    ports:
      - 8080:8080
    depends_on:
      - bg-removal
