spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

http:
  bg-removal:
    base-url: ${BG_REMOVAL_BASE_URL}

bot:
  token: ${BOT_TOKEN}

sticker:
  maxPixelSize: 512
  topPaddingPercent: 15

